on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: liblzma-dev libxml2-dev
          version: 1.0
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --order=random
      - name: Build
        run: shards build
