name: Build and Upload Release Binary

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgc-dev libxml2-dev liblzma-dev

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Build divekit-rv
        run: shards build --release

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: bin/divekit-rv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
