name: Build and Upload Static Release Binary

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies (static build)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgc-dev \
            libxml2-dev \
            liblzma-dev \
            zlib1g-dev \
            pkg-config

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install shards
        run: shards install

      - name: Build static binary
        run: shards build --release --static

      - name: Verify binary type
        run: file bin/divekit-rv

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: bin/divekit-rv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
